import React, { useState } from 'react';
import { ArrowUpRight } from 'lucide-react';

const features = [
  { id: 1, category: 'Intelligence', title: 'AI-Powered Insights', desc: 'Receive personalized financial advice and actionable tips generated by advanced AI models.' },
  { id: 2, category: 'Budgeting', title: 'Smart Budget Limits', desc: 'Set dynamic spending caps based on your income or define custom limits for strict control.' },
  { id: 3, category: 'Analytics', title: 'Visual Spending Trends', desc: 'Understand where your money goes with interactive pie charts and trend analysis.' },
  { id: 4, category: 'Management', title: 'Unified Account View', desc: 'Track balances across savings, cash, and credit cards in a single, editable dashboard.' },
  { id: 5, category: 'Assistant', title: '24/7 Financial Chatbot', desc: 'Ask complex financial questions and get instant, context-aware answers from BudgetBuddy.' },
];

const Features: React.FC = () => {
  const [activeId, setActiveId] = useState<number | null>(null);

  return (
    <section className="py-24 px-6 bg-[#050507]">
      <div className="container mx-auto max-w-6xl">
        <div className="flex flex-col md:flex-row justify-between items-start mb-16">
            <h2 className="text-4xl md:text-5xl font-serif italic leading-tight">
            Built for Tomorrow's <br/>
            <span className="not-italic text-gray-400">Financial Needs</span>
            </h2>
            <div className="mt-6 md:mt-0 animate-spin-slow">
                 <div className="w-12 h-12 text-finora-purple opacity-80">
                    <svg viewBox="0 0 24 24" fill="currentColor">
                        <path d="M12 0L14 10L24 12L14 14L12 24L10 14L0 12L10 10L12 0Z" />
                    </svg>
                 </div>
            </div>
        </div>

        <div className="space-y-2">
          {features.map((feature) => (
            <div 
              key={feature.id}
              onMouseEnter={() => setActiveId(feature.id)}
              onMouseLeave={() => setActiveId(null)}
              className="group relative border-t border-white/10 transition-all duration-300 hover:border-white/30 cursor-pointer"
            >
                {/* Background Hover Effect */}
                <div 
                    className={`absolute inset-0 bg-gradient-to-r from-purple-900/20 to-transparent opacity-0 transition-opacity duration-300 ${activeId === feature.id ? 'opacity-100' : ''}`}
                />

              <div className="relative flex flex-col md:flex-row items-center py-8 md:py-12 px-4 z-10">
                <div className="w-full md:w-1/4 mb-2 md:mb-0">
                  <span className="text-xs uppercase tracking-widest text-gray-500 border border-white/10 rounded-full px-3 py-1">
                    {feature.category}
                  </span>
                </div>
                <div className="w-full md:w-1/2">
                  <h3 className="text-2xl md:text-3xl font-medium mb-2 group-hover:translate-x-2 transition-transform duration-300">
                    {feature.title}
                  </h3>
                  <p className={`text-gray-400 overflow-hidden transition-all duration-300 max-h-0 opacity-0 ${activeId === feature.id ? 'max-h-20 opacity-100 mt-2' : ''}`}>
                    {feature.desc}
                  </p>
                </div>
                <div className="w-full md:w-1/4 flex justify-end opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <ArrowUpRight className="w-8 h-8 text-white" />
                </div>
              </div>
            </div>
          ))}
          <div className="border-t border-white/10" />
        </div>
      </div>
    </section>
  );
};

export default Features;